### ISSUE TITLE
What is the meaning of lines 42-44 in Learn_KoopmanNonlinearA_with_KlinearEig.py

### ISSUE THREAD

**Issue by lee-ck** [HaojieSHI98/DeepKoopmanWithControl#1]
Hello,

I am having trouble understanding the meaning of "torch.mm(U, V.t()) * 0.9" in the code snippet below. Could you please explain the purpose and significance of this process?

```
        self.lA.weight.data = gaussian_init_(Nkoopman, std=1)
        U, _, V = torch.svd(self.lA.weight.data)
        self.lA.weight.data = torch.mm(U, V.t()) * 0.9
```

Thanks a lot.

**Comment by lee-ck** [comment]
I understand

**Comment by ZhuangCCC** [comment]
Recently, I was doing a six-degree-of-freedom robotic arm, and the results were not very good
